project:
  type: book
  output-dir: _book

book:
  # book
  title: R para análisis de datos
  subtitle: Aplicación en la comunidad CLIO (Coopera, Lidera, Innova y Orienta)
  author: 
    - name: 
        given: Luis Francisco 
        family: Gomez Lopez
      affiliations:
        id: umng
        name: Universidad Militar Nueva Granada
      orcid: 0000-0002-2877-9015
  date: 2025-10-29
  date-format: iso
  downloads: [pdf]
  # favicon: pending
  site-url: https://luifrancgom.github.io/r-clio/
  repo-url: https://github.com/luifrancgom/r-clio
  issue-url: https://github.com/luifrancgom/r-clio/issues
  repo-actions: [edit, source, issue]
  sidebar: 
    logo: images/zona-clio-logo.png

  chapters:
    - index.qmd
    - preface.qmd
    - part: first_steps_r.qmd
      chapters: 
        - welcome_to_r.qmd
        - project-oriented_workflow.qmd
        - r_packages.qmd
    - part: data_visualization.qmd
    - part: data_wrangling.qmd
    - part: data_tidy.qmd
    - part: data_import.qmd
    - part: programming.qmd
    - part: data_communication.qmd
    - references.qmd

bibliography: references/r-clio.bib
csl: references/apa.csl
lang: es
editor: source

format:
  html:
    theme:
      - cosmo
      - scss/custom.scss
  pdf:
    # format options
    pdf-engine: lualatex
    # colors
    linkcolor: blue
    filecolor: blue
    citecolor: blue
    urlcolor: blue
    toccolor: blue
    colorlinks: true
    # layout
    documentclass: scrbook
    # references
    link-citations: true
    link-bibliography: true
    # rendering
    keep-tex: false



